### ISSUE TITLE
Server crash when using blocks or items from ThermalLogistics mod

### ISSUE THREAD

**Issue by octo-gone** [Astavie/ThermalLogistics#50]
## Overview

I tried to create a logistic network with Thermal Logistics. This is one of my first networks. I placed terminal, strongbox from Thermal Expansion and tried to connect them but the next exception is caught

```
Time: 2020-11-29 17:30:34 MSK
Description: Exception in server tick loop

java.lang.NullPointerException
    at astavie.thermallogistics.tile.TileTerminalItem$TerminalItemRequester.getRequestedStacks(TileTerminalItem.java:486)
    at astavie.thermallogistics.util.Snapshot.refresh(Snapshot.java:158)
    at astavie.thermallogistics.util.Snapshot.getItems(Snapshot.java:292)
    at astavie.thermallogistics.process.ProcessItem.updateWants(ProcessItem.java:88)
    at astavie.thermallogistics.process.Process.update(Process.java:77)
    at astavie.thermallogistics.attachment.RequesterItem.handleItemSending(RequesterItem.java:89)
    at cofh.thermaldynamics.duct.attachments.servo.ServoItem.tick(ServoItem.java:215)
    at cofh.thermaldynamics.duct.item.GridItem.tickGrid(GridItem.java:80)
    at cofh.thermaldynamics.util.WorldGridList.tickEnd(WorldGridList.java:62)
    at cofh.thermaldynamics.util.TickHandler.tick(TickHandler.java:93)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_438_TickHandler_tick_WorldTickEvent.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
    at net.minecraftforge.fml.common.FMLCommonHandler.onPostWorldTick(FMLCommonHandler.java:274)
    at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:776)
    at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668)
    at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:185)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
    at java.lang.Thread.run(Unknown Source)
```

I recovered the world using mod **Backups** and reproduced it several times. Sometimes errors are caught after removing storage with the connected requester.

**To Reproduce**

1. Place Thermal Logistics Terminal
2. Place storage
3. Connect them with a Thermal Expansion pipe

After reproducing many times my world died finally. I can not load it even with the use of backups (´。＿。｀).

### Versions

- minecraft - 1.12.2
- forge - 14.23.5.2854
- codechickenlib - 3.2.3.357
- redstoneflux - 2.1.1
- cofhcore - 4.6.6
- cofhworld - 1.4.0
- thermalfoundation - 2.6.7
- thermalexpansion - 5.5.7
- thermalcultivation - 0.3.6
- thermaldynamics - 2.5.6
- thermalinnovation - 0.3.6
- **thermallogistics** - 0.3-40

<details>
<summary>More mods versions</summary>

	mcp - 9.42
	FML - 8.0.99.99
	xaerominimap_core - 1.12.2-1.0
	xaeroworldmap_core - 1.12.2-1.0
	backups - 1.5.4
	baubles - 1.5.2
	jei - 4.15.0.281
	forestry - 5.8.2.392
	binniecore - 2.5.1.188
	binniedesign - 2.5.1.188
	genetics - 2.5.1.188
	botany - 2.5.1.188
	extrabees - 2.5.1.188
	extratrees - 2.5.1.188
	biomesoplenty - 7.0.1.2443
	careerbees - 1.0
	ctm - MC1.12.2-1.0.2.31
	chisel - MC1.12.2-1.0.2.45
	computercraft - 1.80pr1
	enchdesc - 1.1.14
	forgelin - 1.8.4
	llibrary - 1.7.19
	fossil - 8.0.3
	fw - 1.6.0
	gendustryjei - 1.0.2
	hammercore - 2.0.6.17
	waila - 1.8.26
	ido - 1.0.6
	jeibees - 0.9.0.5
	jeiintegration - 1.5.1.36
	jrftl - 1.1
	magicbees - 1.0
	netherportalfix - 5.3.17
	particlefixes - 1.0
	retrobees - 1.1.7
	thaumcraft - 6.1.BETA26
	tc6aspects4jei - 0.0.2a
	tcinventoryscan - 2.0.10
	thaumicjei - 1.6.0
	thaumicwaila - 1.12.2-0.0.2
	vanillafix - 1.0.10-SNAPSHOT
	wanionlib - 1.12.2-2.4
	wawla - 2.6.274
	xaerominimap - 20.27.3
	xaeroworldmap - 1.11.1
	unidict - 1.12.2-2.8

</details>

**Comment by Astavie** [comment]
Sorry for not responding sooner -- I deleted my local workspace of TL and it took a lot of time to get Minecraft 1.12 and Java 8 working again.

**Comment by Astavie** [comment]
I couldn't reproduce the bug myself, but the latest version (0.3-41) should have it fixed.

**Comment by octo-gone** [comment]
Thanks for the answer! Ok, I will try the new version. If it appears again I will write again (:
